spring.application.name=connectdb

# ตัว db อยู่ที่ไหน
spring.datasource.url=jdbc:sqlite:C:/Users/KOOKKIK.SWW/Desktop/SQLite-v3.13.1/test_spring_boot.db
# Driver ที่ใช้ในการต่อ db
spring.datasource.driver-class-name=org.sqlite.JDBC
# ใช้ Lib ตัวไหนในการแปลงภาษา sql
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# Jpa สมารถสร้าง Table ให้อัตโนมัติ
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#เปิด debug ของทุก class ใน project
logging.level.root=DEBUG

spring.thymeleaf.cache=false

server.port=8080